### PR TITLE
Wip solution

### PR DESCRIPTION
**Pull request by joshuabamboo**
@AnnJohn @jmburges

### CODE REVIEW

**Comment by joshuabamboo** [comment]
These tests have been rough. I want to figure out a way to test that they do not just have the methods in both classes. I will play around more. Open to suggestions. @jmburges

**Comment by jmburges** [comment]
Does this have the solution in it?

**Comment by jmburges** [comment]
This is the exact same code as what we give them in the previous lab...What do you want the students to do? We should change things up a bit maybe? Also have them write a find_by method that can find_by any hash entries.

**Comment by jmburges** [comment]
and put it in the super class

**Comment by joshuabamboo** [comment]
It has the solution. This PR is for the solution branch.

**Comment by joshuabamboo** [comment]
The solution is the same as the readme solution where they are introduced to a dynamic orm. They haven't done a lab yet. We are making a readme/lab combo. The idea is that building a dynamic orm is going to be extremely tough for them, especially as remote learners. Therefore, we do a hand-holding walk-through (readme), and then let them take a stab at it with tests (lab). Not sure how much changing it up we can do with a dynamic orm.

**Comment by joshuabamboo** [comment]
I'll add a find_by

**Comment by joshuabamboo** [comment]
Back to you @jmburges

**Comment by jmburges** [comment]
:shipit:

**Pull request merged**
